### ISSUE TITLE
Webpack + Readium

### ISSUE THREAD

**Issue by bradleygore** [clebeaupin/readium-electron#1]
Hi, thanks for publishing this repo - I'm finding it super helpful!

I'm working on a web app that is using Webpack and need to pull in ReadiumJS, and using your webpack readium config as a baseline.  I'm curious to understand a couple things, however:

1) Why always use the plain fetcher and expect an epub to be exploded (code [here](https://github.com/clebeaupin/readium-electron/blob/master/webpack.config.readium.js#L53))?
2) I also see that you have a [custom zip loader](https://github.com/clebeaupin/readium-electron/blob/master/webpack.config.zip.js) and appear to be using it to parse zipped epubs before handing off to Readium. Is there a specific reason for this - i.e. is there something I should watch out for if using Readium's default zip fetcher in my web app?

Apologies for posting this in an issue, but I didn't see an email address at which to contact. Any insight you can provide is greatly appreciated 😄

**Comment by clebeaupin** [comment]
This is an old POC. We are working now on a real application that is still in development github.com/edrlab/readium-desktop

1. We use plain fetcher to make sure that the renderer process (view) will no try to explode itself the epub. Epub must be served by the main process from a registered protocol

2. this zip library is not used when using the feature branch feature/readium-sdk. This is only used on the master branch because there is no readium sdk to read the epub content
